# Site settings
title: Alexandre Kazuo Sato - Info Page
email: aksato.br@gmail.com
description: The Jekyll version of the Identity theme by HTML5 UP.
baseurl: "/identity-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Identity
your-name: Alexandre Kazuo Sato
your-title: Cloud Infrastructure Architect

# Social settings
500px_url:
facebook_url: https://facebook.com
github_url: https://github.com/aksatobr 
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/alexandresato/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/aksatobr

# Build settings
markdown: kramdown
